# Generated by Django 5.0.2 on 2024-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('partday', models.CharField(max_length=100)),
                ('prefsport', models.CharField(max_length=100)),
                ('consume', models.CharField(max_length=100)),
                ('prodtype', models.CharField(max_length=100)),
                ('bodytype', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
