# Generated by Django 5.0.2 on 2024-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_surmodel_your_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surmodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surmodel',
            name='prefsport',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='surmodel',
            name='prodtype',
            field=models.CharField(max_length=500),
        ),
    ]
