# Generated by Django 5.0.2 on 2024-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='url',
            new_name='img',
        ),
        migrations.AddField(
            model_name='catalog',
            name='sch',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
